/**
 * Tests for compat.ts — backward compatibility migration of ~/.vetkey-tool/
 *
 * Verifies:
 *   - No-op when legacy directory does not exist
 *   - Only .pid, .sock, .log files are migrated (whitelist)
 *   - Non-runtime files (.DS_Store, etc.) are left behind
 *   - Files already present in new directory are NOT overwritten
 *   - Old directory is removed when empty after migration
 *   - Idempotent — safe to call multiple times
 *
 * Uses real temporary directories for integration-style tests.
 */

import fs from 'fs';
import os from 'os';
import path from 'path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

// Mock os.homedir() so tests use a temp directory instead of real home
const { mockHomedir } = vi.hoisted(() => ({
  mockHomedir: vi.fn(),
}));

vi.mock('os', async (importOriginal) => {
  const actual = await importOriginal<typeof import('os')>();
  return { ...actual, homedir: mockHomedir };
});

// Suppress log output during tests
vi.mock('../log.js', () => ({
  debug: vi.fn(),
  info: vi.fn(),
  warn: vi.fn(),
  error: vi.fn(),
}));

import { migrateLegacyRuntimeDir } from '../compat.js';
import { legacyRuntimeDir, runtimeDir } from '../paths.js';

describe('migrateLegacyRuntimeDir', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'zcloak-compat-test-'));
    mockHomedir.mockReturnValue(tmpDir);
  });

  afterEach(() => {
    vi.clearAllMocks();
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('does nothing when legacy directory does not exist', () => {
    expect(() => migrateLegacyRuntimeDir()).not.toThrow();
    // New directory should NOT be created if there's nothing to migrate
    expect(fs.existsSync(runtimeDir())).toBe(false);
  });

  it('moves .pid, .sock, and .log files to new directory', () => {
    const oldDir = legacyRuntimeDir();
    fs.mkdirSync(oldDir, { recursive: true });

    // Create sample daemon runtime files
    fs.writeFileSync(path.join(oldDir, 'principal_default.pid'), '12345\n');
    fs.writeFileSync(path.join(oldDir, 'principal_default.sock'), '');
    fs.writeFileSync(path.join(oldDir, 'default-daemon.log'), 'log content');

    migrateLegacyRuntimeDir();

    const newDir = runtimeDir();
    expect(fs.existsSync(path.join(newDir, 'principal_default.pid'))).toBe(true);
    expect(fs.existsSync(path.join(newDir, 'principal_default.sock'))).toBe(true);
    expect(fs.existsSync(path.join(newDir, 'default-daemon.log'))).toBe(true);

    // Content should be preserved
    expect(fs.readFileSync(path.join(newDir, 'principal_default.pid'), 'utf-8')).toBe('12345\n');

    // Old directory should be removed (only runtime files existed, all migrated)
    expect(fs.existsSync(oldDir)).toBe(false);
  });

  it('skips non-runtime files (.DS_Store, backups, etc.)', () => {
    const oldDir = legacyRuntimeDir();
    fs.mkdirSync(oldDir, { recursive: true });

    // Runtime file — should be migrated
    fs.writeFileSync(path.join(oldDir, 'test.pid'), '1');
    // Non-runtime files — should be left behind
    fs.writeFileSync(path.join(oldDir, '.DS_Store'), '');
    fs.writeFileSync(path.join(oldDir, 'notes.txt'), 'memo');
    fs.writeFileSync(path.join(oldDir, 'backup.bak'), 'old data');

    migrateLegacyRuntimeDir();

    const newDir = runtimeDir();
    // Runtime file migrated
    expect(fs.existsSync(path.join(newDir, 'test.pid'))).toBe(true);
    // Non-runtime files NOT migrated
    expect(fs.existsSync(path.join(newDir, '.DS_Store'))).toBe(false);
    expect(fs.existsSync(path.join(newDir, 'notes.txt'))).toBe(false);
    expect(fs.existsSync(path.join(newDir, 'backup.bak'))).toBe(false);

    // Old directory still exists (non-runtime files remain)
    expect(fs.existsSync(oldDir)).toBe(true);
    expect(fs.existsSync(path.join(oldDir, '.DS_Store'))).toBe(true);
  });

  it('does NOT overwrite files already in new directory', () => {
    const oldDir = legacyRuntimeDir();
    const newDir = runtimeDir();
    fs.mkdirSync(oldDir, { recursive: true });
    fs.mkdirSync(newDir, { recursive: true, mode: 0o700 });

    // Old directory has a stale PID file
    fs.writeFileSync(path.join(oldDir, 'daemon.pid'), 'old-pid-111\n');
    // New directory already has a fresh PID file (regenerated by daemon on new path)
    fs.writeFileSync(path.join(newDir, 'daemon.pid'), 'new-pid-222\n');

    migrateLegacyRuntimeDir();

    // New file should NOT be overwritten — its content should remain unchanged
    expect(fs.readFileSync(path.join(newDir, 'daemon.pid'), 'utf-8')).toBe('new-pid-222\n');
    // Old file should still be in old dir (it was skipped, not deleted)
    expect(fs.existsSync(path.join(oldDir, 'daemon.pid'))).toBe(true);
  });

  it('creates new directory with 0o700 permissions', () => {
    const oldDir = legacyRuntimeDir();
    fs.mkdirSync(oldDir, { recursive: true });
    fs.writeFileSync(path.join(oldDir, 'test.pid'), '1');

    migrateLegacyRuntimeDir();

    const newDir = runtimeDir();
    expect(fs.existsSync(newDir)).toBe(true);
    const stats = fs.statSync(newDir);
    expect(stats.mode & 0o777).toBe(0o700);
  });

  it('is idempotent — second call is a no-op', () => {
    const oldDir = legacyRuntimeDir();
    fs.mkdirSync(oldDir, { recursive: true });
    fs.writeFileSync(path.join(oldDir, 'test.pid'), '1');

    migrateLegacyRuntimeDir();
    // Old dir was removed — second call should be a silent no-op
    expect(() => migrateLegacyRuntimeDir()).not.toThrow();

    // File should still be in new location
    expect(fs.existsSync(path.join(runtimeDir(), 'test.pid'))).toBe(true);
  });

  it('keeps old directory when unmovable files remain', () => {
    const oldDir = legacyRuntimeDir();
    const newDir = runtimeDir();
    fs.mkdirSync(oldDir, { recursive: true });
    fs.mkdirSync(newDir, { recursive: true, mode: 0o700 });

    // A .pid file that can be migrated
    fs.writeFileSync(path.join(oldDir, 'moveable.pid'), '1');
    // A .sock file that already exists in new dir — will be skipped
    fs.writeFileSync(path.join(oldDir, 'active.sock'), 'old');
    fs.writeFileSync(path.join(newDir, 'active.sock'), 'new');

    migrateLegacyRuntimeDir();

    // moveable.pid should be in new dir
    expect(fs.existsSync(path.join(newDir, 'moveable.pid'))).toBe(true);
    // active.sock in new dir should still have the new content
    expect(fs.readFileSync(path.join(newDir, 'active.sock'), 'utf-8')).toBe('new');
    // Old directory should still exist (active.sock was skipped)
    expect(fs.existsSync(oldDir)).toBe(true);
    expect(fs.existsSync(path.join(oldDir, 'active.sock'))).toBe(true);
  });
});
