/**
 * Backward compatibility — migrate legacy ~/.vetkey-tool/ to ~/.config/zcloak/run/
 *
 * This module is a standalone migration helper. It can be safely removed
 * once all users have been migrated (after a few release cycles).
 *
 * Migration logic:
 *   1. If ~/.vetkey-tool/ does not exist → nothing to do
 *   2. If ~/.config/zcloak/run/ does not exist → create it
 *   3. Move all files (*.pid, *.sock, *-daemon.log) from old dir to new dir
 *   4. Remove the old directory if it's now empty
 *   5. Log a one-time migration notice
 *
 * This function is idempotent — safe to call multiple times.
 *
 * NOTE: When removing this file, also remove:
 *   - The `legacyRuntimeDir()` export from src/paths.ts
 *   - The `migrateLegacyRuntimeDir()` call from src/cli.ts
 */

import { existsSync, mkdirSync, readdirSync, renameSync, rmdirSync } from 'fs';
import { join, extname } from 'path';
import { legacyRuntimeDir, runtimeDir } from './paths.js';
import * as log from './log.js';

/**
 * File extensions that belong to daemon runtime artifacts.
 * Only files matching these extensions are migrated; everything else
 * (.DS_Store, editor backups, etc.) is left in the old directory.
 */
const MIGRATABLE_EXTENSIONS = new Set(['.pid', '.sock', '.log']);

/**
 * Migrate daemon runtime files from the legacy directory (~/.vetkey-tool/)
 * to the new unified location (~/.config/zcloak/run/).
 *
 * - Only moves .pid, .sock, and .log files (whitelist filter)
 * - Skips files that already exist in the new directory to avoid
 *   overwriting active daemon artifacts regenerated after a partial migration
 * - Skips files that cannot be moved (e.g. in-use sockets)
 * - Removes the old directory if empty after migration
 * - Idempotent: safe to call on every CLI invocation
 */
export function migrateLegacyRuntimeDir(): void {
  const oldDir = legacyRuntimeDir();

  // Nothing to migrate if old directory doesn't exist
  if (!existsSync(oldDir)) return;

  const newDir = runtimeDir();
  if (!existsSync(newDir)) {
    mkdirSync(newDir, { recursive: true, mode: 0o700 });
  }

  try {
    const files = readdirSync(oldDir);
    for (const file of files) {
      // Whitelist: only migrate known daemon runtime file types
      if (!MIGRATABLE_EXTENSIONS.has(extname(file))) {
        log.debug(`compat: skipping non-runtime file ${file}`);
        continue;
      }

      const dst = join(newDir, file);

      // Never overwrite: if the file already exists in the new directory,
      // it was regenerated by a daemon running on the new path — the old
      // copy is stale and should just be left for cleanup.
      if (existsSync(dst)) {
        log.debug(`compat: ${file} already exists in new dir, skipping`);
        continue;
      }

      const src = join(oldDir, file);
      try {
        renameSync(src, dst);
      } catch {
        // File may be in use by an active daemon — skip silently.
        // It will be picked up on the next CLI invocation after the daemon restarts.
        log.debug(`compat: could not move ${src} → ${dst}, skipping (file may be in use)`);
      }
    }

    // Try to remove the old directory if it's now empty
    try {
      rmdirSync(oldDir);
      log.info('Migrated daemon runtime files from ~/.vetkey-tool/ to ~/.config/zcloak/run/');
    } catch {
      // Directory not empty (non-runtime files or skipped files remain) — that's fine.
      log.debug('compat: ~/.vetkey-tool/ not empty yet, will retry on next run');
    }
  } catch (e) {
    // Migration is best-effort — never block the CLI
    log.debug(`compat: migration failed: ${e instanceof Error ? e.message : String(e)}`);
  }
}
